[package]
name = "screech"
version = "0.1.0"
authors = ["trevp"]

[features]
default = ["rand", "rust-crypto"]

[dependencies]
byteorder = "0.5"
rand = { version = "0.3", optional = true }
rust-crypto = { version = "0.2", optional = true }

[dev-dependencies]
rustc-serialize = "0.3"
